#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Capa_Datos
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="DbMonolito")]
	public partial class DbMonolitoDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Definiciones de métodos de extensibilidad
    partial void OnCreated();
    partial void InsertUsers(Users instance);
    partial void UpdateUsers(Users instance);
    partial void DeleteUsers(Users instance);
    partial void InsertHistorialAccesos(HistorialAccesos instance);
    partial void UpdateHistorialAccesos(HistorialAccesos instance);
    partial void DeleteHistorialAccesos(HistorialAccesos instance);
    partial void InsertUserTypes(UserTypes instance);
    partial void UpdateUserTypes(UserTypes instance);
    partial void DeleteUserTypes(UserTypes instance);
    partial void InsertFotosUsuario(FotosUsuario instance);
    partial void UpdateFotosUsuario(FotosUsuario instance);
    partial void DeleteFotosUsuario(FotosUsuario instance);
    partial void Inserttbl_proveedor(tbl_proveedor instance);
    partial void Updatetbl_proveedor(tbl_proveedor instance);
    partial void Deletetbl_proveedor(tbl_proveedor instance);
    partial void Inserttbl_categoria_permitida(tbl_categoria_permitida instance);
    partial void Updatetbl_categoria_permitida(tbl_categoria_permitida instance);
    partial void Deletetbl_categoria_permitida(tbl_categoria_permitida instance);
    partial void Inserttbl_proveedor_categoria(tbl_proveedor_categoria instance);
    partial void Updatetbl_proveedor_categoria(tbl_proveedor_categoria instance);
    partial void Deletetbl_proveedor_categoria(tbl_proveedor_categoria instance);
    partial void Inserttbl_categoria(tbl_categoria instance);
    partial void Updatetbl_categoria(tbl_categoria instance);
    partial void Deletetbl_categoria(tbl_categoria instance);
    partial void Inserttbl_producto(tbl_producto instance);
    partial void Updatetbl_producto(tbl_producto instance);
    partial void Deletetbl_producto(tbl_producto instance);
    partial void Inserttbl_producto_imagen(tbl_producto_imagen instance);
    partial void Updatetbl_producto_imagen(tbl_producto_imagen instance);
    partial void Deletetbl_producto_imagen(tbl_producto_imagen instance);
    #endregion
		
		public DbMonolitoDataContext() : 
				base(global::Capa_Datos.Properties.Settings.Default.DbMonolitoConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DbMonolitoDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DbMonolitoDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DbMonolitoDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DbMonolitoDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Users> Users
		{
			get
			{
				return this.GetTable<Users>();
			}
		}
		
		public System.Data.Linq.Table<HistorialAccesos> HistorialAccesos
		{
			get
			{
				return this.GetTable<HistorialAccesos>();
			}
		}
		
		public System.Data.Linq.Table<UserTypes> UserTypes
		{
			get
			{
				return this.GetTable<UserTypes>();
			}
		}
		
		public System.Data.Linq.Table<FotosUsuario> FotosUsuario
		{
			get
			{
				return this.GetTable<FotosUsuario>();
			}
		}
		
		public System.Data.Linq.Table<tbl_proveedor> tbl_proveedor
		{
			get
			{
				return this.GetTable<tbl_proveedor>();
			}
		}
		
		public System.Data.Linq.Table<tbl_categoria_permitida> tbl_categoria_permitida
		{
			get
			{
				return this.GetTable<tbl_categoria_permitida>();
			}
		}
		
		public System.Data.Linq.Table<tbl_proveedor_categoria> tbl_proveedor_categoria
		{
			get
			{
				return this.GetTable<tbl_proveedor_categoria>();
			}
		}
		
		public System.Data.Linq.Table<tbl_categoria> tbl_categoria
		{
			get
			{
				return this.GetTable<tbl_categoria>();
			}
		}
		
		public System.Data.Linq.Table<tbl_producto> tbl_producto
		{
			get
			{
				return this.GetTable<tbl_producto>();
			}
		}
		
		public System.Data.Linq.Table<tbl_producto_imagen> tbl_producto_imagen
		{
			get
			{
				return this.GetTable<tbl_producto_imagen>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Users")]
	public partial class Users : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IdUser;
		
		private string _tbl_nombre;
		
		private string _tbl_apellido;
		
		private System.DateTime _tbl_fecha;
		
		private string _tbl_email;
		
		private string _tbl_cedula;
		
		private string _tbl_celular;
		
		private string _tbl_nickame;
		
		private System.Data.Linq.Binary _tbl_PasswordHash;
		
		private string _tbl_genero;
		
		private System.Nullable<System.DateTime> _tbl_fecha_de_registro;
		
		private System.Nullable<bool> _tbl_activo;
		
		private System.Data.Linq.Binary _tbl_foto;
		
		private string _tbl_direccion;
		
		private System.Nullable<int> _tbl_numerodeintentos_fallidos;
		
		private string _tbl_OtpCode;
		
		private System.Nullable<int> _tbl_UsertypeID;
		
		private System.Nullable<System.DateTime> _tbl_ultimo_intento;
		
		private EntitySet<HistorialAccesos> _HistorialAccesos;
		
		private EntitySet<FotosUsuario> _FotosUsuario;
		
		private EntityRef<UserTypes> _UserTypes;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdUserChanging(int value);
    partial void OnIdUserChanged();
    partial void Ontbl_nombreChanging(string value);
    partial void Ontbl_nombreChanged();
    partial void Ontbl_apellidoChanging(string value);
    partial void Ontbl_apellidoChanged();
    partial void Ontbl_fechaChanging(System.DateTime value);
    partial void Ontbl_fechaChanged();
    partial void Ontbl_emailChanging(string value);
    partial void Ontbl_emailChanged();
    partial void Ontbl_cedulaChanging(string value);
    partial void Ontbl_cedulaChanged();
    partial void Ontbl_celularChanging(string value);
    partial void Ontbl_celularChanged();
    partial void Ontbl_nickameChanging(string value);
    partial void Ontbl_nickameChanged();
    partial void Ontbl_PasswordHashChanging(System.Data.Linq.Binary value);
    partial void Ontbl_PasswordHashChanged();
    partial void Ontbl_generoChanging(string value);
    partial void Ontbl_generoChanged();
    partial void Ontbl_fecha_de_registroChanging(System.Nullable<System.DateTime> value);
    partial void Ontbl_fecha_de_registroChanged();
    partial void Ontbl_activoChanging(System.Nullable<bool> value);
    partial void Ontbl_activoChanged();
    partial void Ontbl_fotoChanging(System.Data.Linq.Binary value);
    partial void Ontbl_fotoChanged();
    partial void Ontbl_direccionChanging(string value);
    partial void Ontbl_direccionChanged();
    partial void Ontbl_numerodeintentos_fallidosChanging(System.Nullable<int> value);
    partial void Ontbl_numerodeintentos_fallidosChanged();
    partial void Ontbl_OtpCodeChanging(string value);
    partial void Ontbl_OtpCodeChanged();
    partial void Ontbl_UsertypeIDChanging(System.Nullable<int> value);
    partial void Ontbl_UsertypeIDChanged();
    partial void Ontbl_ultimo_intentoChanging(System.Nullable<System.DateTime> value);
    partial void Ontbl_ultimo_intentoChanged();
    #endregion
		
		public Users()
		{
			this._HistorialAccesos = new EntitySet<HistorialAccesos>(new Action<HistorialAccesos>(this.attach_HistorialAccesos), new Action<HistorialAccesos>(this.detach_HistorialAccesos));
			this._FotosUsuario = new EntitySet<FotosUsuario>(new Action<FotosUsuario>(this.attach_FotosUsuario), new Action<FotosUsuario>(this.detach_FotosUsuario));
			this._UserTypes = default(EntityRef<UserTypes>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdUser", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int IdUser
		{
			get
			{
				return this._IdUser;
			}
			set
			{
				if ((this._IdUser != value))
				{
					this.OnIdUserChanging(value);
					this.SendPropertyChanging();
					this._IdUser = value;
					this.SendPropertyChanged("IdUser");
					this.OnIdUserChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tbl_nombre", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string tbl_nombre
		{
			get
			{
				return this._tbl_nombre;
			}
			set
			{
				if ((this._tbl_nombre != value))
				{
					this.Ontbl_nombreChanging(value);
					this.SendPropertyChanging();
					this._tbl_nombre = value;
					this.SendPropertyChanged("tbl_nombre");
					this.Ontbl_nombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tbl_apellido", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string tbl_apellido
		{
			get
			{
				return this._tbl_apellido;
			}
			set
			{
				if ((this._tbl_apellido != value))
				{
					this.Ontbl_apellidoChanging(value);
					this.SendPropertyChanging();
					this._tbl_apellido = value;
					this.SendPropertyChanged("tbl_apellido");
					this.Ontbl_apellidoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tbl_fecha", DbType="Date NOT NULL")]
		public System.DateTime tbl_fecha
		{
			get
			{
				return this._tbl_fecha;
			}
			set
			{
				if ((this._tbl_fecha != value))
				{
					this.Ontbl_fechaChanging(value);
					this.SendPropertyChanging();
					this._tbl_fecha = value;
					this.SendPropertyChanged("tbl_fecha");
					this.Ontbl_fechaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tbl_email", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string tbl_email
		{
			get
			{
				return this._tbl_email;
			}
			set
			{
				if ((this._tbl_email != value))
				{
					this.Ontbl_emailChanging(value);
					this.SendPropertyChanging();
					this._tbl_email = value;
					this.SendPropertyChanged("tbl_email");
					this.Ontbl_emailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tbl_cedula", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string tbl_cedula
		{
			get
			{
				return this._tbl_cedula;
			}
			set
			{
				if ((this._tbl_cedula != value))
				{
					this.Ontbl_cedulaChanging(value);
					this.SendPropertyChanging();
					this._tbl_cedula = value;
					this.SendPropertyChanged("tbl_cedula");
					this.Ontbl_cedulaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tbl_celular", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string tbl_celular
		{
			get
			{
				return this._tbl_celular;
			}
			set
			{
				if ((this._tbl_celular != value))
				{
					this.Ontbl_celularChanging(value);
					this.SendPropertyChanging();
					this._tbl_celular = value;
					this.SendPropertyChanged("tbl_celular");
					this.Ontbl_celularChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tbl_nickame", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string tbl_nickame
		{
			get
			{
				return this._tbl_nickame;
			}
			set
			{
				if ((this._tbl_nickame != value))
				{
					this.Ontbl_nickameChanging(value);
					this.SendPropertyChanging();
					this._tbl_nickame = value;
					this.SendPropertyChanged("tbl_nickame");
					this.Ontbl_nickameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tbl_PasswordHash", DbType="VarBinary(MAX) NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary tbl_PasswordHash
		{
			get
			{
				return this._tbl_PasswordHash;
			}
			set
			{
				if ((this._tbl_PasswordHash != value))
				{
					this.Ontbl_PasswordHashChanging(value);
					this.SendPropertyChanging();
					this._tbl_PasswordHash = value;
					this.SendPropertyChanged("tbl_PasswordHash");
					this.Ontbl_PasswordHashChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tbl_genero", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string tbl_genero
		{
			get
			{
				return this._tbl_genero;
			}
			set
			{
				if ((this._tbl_genero != value))
				{
					this.Ontbl_generoChanging(value);
					this.SendPropertyChanging();
					this._tbl_genero = value;
					this.SendPropertyChanged("tbl_genero");
					this.Ontbl_generoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tbl_fecha_de_registro", DbType="DateTime")]
		public System.Nullable<System.DateTime> tbl_fecha_de_registro
		{
			get
			{
				return this._tbl_fecha_de_registro;
			}
			set
			{
				if ((this._tbl_fecha_de_registro != value))
				{
					this.Ontbl_fecha_de_registroChanging(value);
					this.SendPropertyChanging();
					this._tbl_fecha_de_registro = value;
					this.SendPropertyChanged("tbl_fecha_de_registro");
					this.Ontbl_fecha_de_registroChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tbl_activo", DbType="Bit")]
		public System.Nullable<bool> tbl_activo
		{
			get
			{
				return this._tbl_activo;
			}
			set
			{
				if ((this._tbl_activo != value))
				{
					this.Ontbl_activoChanging(value);
					this.SendPropertyChanging();
					this._tbl_activo = value;
					this.SendPropertyChanged("tbl_activo");
					this.Ontbl_activoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tbl_foto", DbType="VarBinary(MAX)", UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary tbl_foto
		{
			get
			{
				return this._tbl_foto;
			}
			set
			{
				if ((this._tbl_foto != value))
				{
					this.Ontbl_fotoChanging(value);
					this.SendPropertyChanging();
					this._tbl_foto = value;
					this.SendPropertyChanged("tbl_foto");
					this.Ontbl_fotoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tbl_direccion", DbType="VarChar(255)")]
		public string tbl_direccion
		{
			get
			{
				return this._tbl_direccion;
			}
			set
			{
				if ((this._tbl_direccion != value))
				{
					this.Ontbl_direccionChanging(value);
					this.SendPropertyChanging();
					this._tbl_direccion = value;
					this.SendPropertyChanged("tbl_direccion");
					this.Ontbl_direccionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tbl_numerodeintentos_fallidos", DbType="Int")]
		public System.Nullable<int> tbl_numerodeintentos_fallidos
		{
			get
			{
				return this._tbl_numerodeintentos_fallidos;
			}
			set
			{
				if ((this._tbl_numerodeintentos_fallidos != value))
				{
					this.Ontbl_numerodeintentos_fallidosChanging(value);
					this.SendPropertyChanging();
					this._tbl_numerodeintentos_fallidos = value;
					this.SendPropertyChanged("tbl_numerodeintentos_fallidos");
					this.Ontbl_numerodeintentos_fallidosChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tbl_OtpCode", DbType="VarChar(MAX)")]
		public string tbl_OtpCode
		{
			get
			{
				return this._tbl_OtpCode;
			}
			set
			{
				if ((this._tbl_OtpCode != value))
				{
					this.Ontbl_OtpCodeChanging(value);
					this.SendPropertyChanging();
					this._tbl_OtpCode = value;
					this.SendPropertyChanged("tbl_OtpCode");
					this.Ontbl_OtpCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tbl_UsertypeID", DbType="Int")]
		public System.Nullable<int> tbl_UsertypeID
		{
			get
			{
				return this._tbl_UsertypeID;
			}
			set
			{
				if ((this._tbl_UsertypeID != value))
				{
					if (this._UserTypes.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Ontbl_UsertypeIDChanging(value);
					this.SendPropertyChanging();
					this._tbl_UsertypeID = value;
					this.SendPropertyChanged("tbl_UsertypeID");
					this.Ontbl_UsertypeIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tbl_ultimo_intento", DbType="DateTime")]
		public System.Nullable<System.DateTime> tbl_ultimo_intento
		{
			get
			{
				return this._tbl_ultimo_intento;
			}
			set
			{
				if ((this._tbl_ultimo_intento != value))
				{
					this.Ontbl_ultimo_intentoChanging(value);
					this.SendPropertyChanging();
					this._tbl_ultimo_intento = value;
					this.SendPropertyChanged("tbl_ultimo_intento");
					this.Ontbl_ultimo_intentoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Users_HistorialAccesos", Storage="_HistorialAccesos", ThisKey="IdUser", OtherKey="IdUser")]
		public EntitySet<HistorialAccesos> HistorialAccesos
		{
			get
			{
				return this._HistorialAccesos;
			}
			set
			{
				this._HistorialAccesos.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Users_FotosUsuario", Storage="_FotosUsuario", ThisKey="IdUser", OtherKey="IdUser")]
		public EntitySet<FotosUsuario> FotosUsuario
		{
			get
			{
				return this._FotosUsuario;
			}
			set
			{
				this._FotosUsuario.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="UserTypes_Users", Storage="_UserTypes", ThisKey="tbl_UsertypeID", OtherKey="Id", IsForeignKey=true)]
		public UserTypes UserTypes
		{
			get
			{
				return this._UserTypes.Entity;
			}
			set
			{
				UserTypes previousValue = this._UserTypes.Entity;
				if (((previousValue != value) 
							|| (this._UserTypes.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._UserTypes.Entity = null;
						previousValue.Users.Remove(this);
					}
					this._UserTypes.Entity = value;
					if ((value != null))
					{
						value.Users.Add(this);
						this._tbl_UsertypeID = value.Id;
					}
					else
					{
						this._tbl_UsertypeID = default(Nullable<int>);
					}
					this.SendPropertyChanged("UserTypes");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_HistorialAccesos(HistorialAccesos entity)
		{
			this.SendPropertyChanging();
			entity.Users = this;
		}
		
		private void detach_HistorialAccesos(HistorialAccesos entity)
		{
			this.SendPropertyChanging();
			entity.Users = null;
		}
		
		private void attach_FotosUsuario(FotosUsuario entity)
		{
			this.SendPropertyChanging();
			entity.Users = this;
		}
		
		private void detach_FotosUsuario(FotosUsuario entity)
		{
			this.SendPropertyChanging();
			entity.Users = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.HistorialAccesos")]
	public partial class HistorialAccesos : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IdLog;
		
		private int _IdUser;
		
		private System.Nullable<System.DateTime> _FechaIngreso;
		
		private EntityRef<Users> _Users;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdLogChanging(int value);
    partial void OnIdLogChanged();
    partial void OnIdUserChanging(int value);
    partial void OnIdUserChanged();
    partial void OnFechaIngresoChanging(System.Nullable<System.DateTime> value);
    partial void OnFechaIngresoChanged();
    #endregion
		
		public HistorialAccesos()
		{
			this._Users = default(EntityRef<Users>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdLog", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int IdLog
		{
			get
			{
				return this._IdLog;
			}
			set
			{
				if ((this._IdLog != value))
				{
					this.OnIdLogChanging(value);
					this.SendPropertyChanging();
					this._IdLog = value;
					this.SendPropertyChanged("IdLog");
					this.OnIdLogChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdUser", DbType="Int NOT NULL")]
		public int IdUser
		{
			get
			{
				return this._IdUser;
			}
			set
			{
				if ((this._IdUser != value))
				{
					if (this._Users.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIdUserChanging(value);
					this.SendPropertyChanging();
					this._IdUser = value;
					this.SendPropertyChanged("IdUser");
					this.OnIdUserChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaIngreso", DbType="DateTime")]
		public System.Nullable<System.DateTime> FechaIngreso
		{
			get
			{
				return this._FechaIngreso;
			}
			set
			{
				if ((this._FechaIngreso != value))
				{
					this.OnFechaIngresoChanging(value);
					this.SendPropertyChanging();
					this._FechaIngreso = value;
					this.SendPropertyChanged("FechaIngreso");
					this.OnFechaIngresoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Users_HistorialAccesos", Storage="_Users", ThisKey="IdUser", OtherKey="IdUser", IsForeignKey=true)]
		public Users Users
		{
			get
			{
				return this._Users.Entity;
			}
			set
			{
				Users previousValue = this._Users.Entity;
				if (((previousValue != value) 
							|| (this._Users.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Users.Entity = null;
						previousValue.HistorialAccesos.Remove(this);
					}
					this._Users.Entity = value;
					if ((value != null))
					{
						value.HistorialAccesos.Add(this);
						this._IdUser = value.IdUser;
					}
					else
					{
						this._IdUser = default(int);
					}
					this.SendPropertyChanged("Users");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.UserTypes")]
	public partial class UserTypes : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _TypeName;
		
		private EntitySet<Users> _Users;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnTypeNameChanging(string value);
    partial void OnTypeNameChanged();
    #endregion
		
		public UserTypes()
		{
			this._Users = new EntitySet<Users>(new Action<Users>(this.attach_Users), new Action<Users>(this.detach_Users));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TypeName", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string TypeName
		{
			get
			{
				return this._TypeName;
			}
			set
			{
				if ((this._TypeName != value))
				{
					this.OnTypeNameChanging(value);
					this.SendPropertyChanging();
					this._TypeName = value;
					this.SendPropertyChanged("TypeName");
					this.OnTypeNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="UserTypes_Users", Storage="_Users", ThisKey="Id", OtherKey="tbl_UsertypeID")]
		public EntitySet<Users> Users
		{
			get
			{
				return this._Users;
			}
			set
			{
				this._Users.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Users(Users entity)
		{
			this.SendPropertyChanging();
			entity.UserTypes = this;
		}
		
		private void detach_Users(Users entity)
		{
			this.SendPropertyChanging();
			entity.UserTypes = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.FotosUsuario")]
	public partial class FotosUsuario : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IdFoto;
		
		private int _IdUser;
		
		private System.Data.Linq.Binary _FotoBinario;
		
		private System.Nullable<System.DateTime> _FechaSubida;
		
		private EntityRef<Users> _Users;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdFotoChanging(int value);
    partial void OnIdFotoChanged();
    partial void OnIdUserChanging(int value);
    partial void OnIdUserChanged();
    partial void OnFotoBinarioChanging(System.Data.Linq.Binary value);
    partial void OnFotoBinarioChanged();
    partial void OnFechaSubidaChanging(System.Nullable<System.DateTime> value);
    partial void OnFechaSubidaChanged();
    #endregion
		
		public FotosUsuario()
		{
			this._Users = default(EntityRef<Users>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdFoto", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int IdFoto
		{
			get
			{
				return this._IdFoto;
			}
			set
			{
				if ((this._IdFoto != value))
				{
					this.OnIdFotoChanging(value);
					this.SendPropertyChanging();
					this._IdFoto = value;
					this.SendPropertyChanged("IdFoto");
					this.OnIdFotoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdUser", DbType="Int NOT NULL")]
		public int IdUser
		{
			get
			{
				return this._IdUser;
			}
			set
			{
				if ((this._IdUser != value))
				{
					if (this._Users.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIdUserChanging(value);
					this.SendPropertyChanging();
					this._IdUser = value;
					this.SendPropertyChanged("IdUser");
					this.OnIdUserChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FotoBinario", DbType="VarBinary(MAX) NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary FotoBinario
		{
			get
			{
				return this._FotoBinario;
			}
			set
			{
				if ((this._FotoBinario != value))
				{
					this.OnFotoBinarioChanging(value);
					this.SendPropertyChanging();
					this._FotoBinario = value;
					this.SendPropertyChanged("FotoBinario");
					this.OnFotoBinarioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaSubida", DbType="DateTime")]
		public System.Nullable<System.DateTime> FechaSubida
		{
			get
			{
				return this._FechaSubida;
			}
			set
			{
				if ((this._FechaSubida != value))
				{
					this.OnFechaSubidaChanging(value);
					this.SendPropertyChanging();
					this._FechaSubida = value;
					this.SendPropertyChanged("FechaSubida");
					this.OnFechaSubidaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Users_FotosUsuario", Storage="_Users", ThisKey="IdUser", OtherKey="IdUser", IsForeignKey=true)]
		public Users Users
		{
			get
			{
				return this._Users.Entity;
			}
			set
			{
				Users previousValue = this._Users.Entity;
				if (((previousValue != value) 
							|| (this._Users.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Users.Entity = null;
						previousValue.FotosUsuario.Remove(this);
					}
					this._Users.Entity = value;
					if ((value != null))
					{
						value.FotosUsuario.Add(this);
						this._IdUser = value.IdUser;
					}
					else
					{
						this._IdUser = default(int);
					}
					this.SendPropertyChanged("Users");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_proveedor")]
	public partial class tbl_proveedor : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _prov_id;
		
		private string _prov_nombre;
		
		private string _prov_contacto;
		
		private string _prov_email;
		
		private System.Nullable<bool> _prov_estado;
		
		private System.Nullable<System.DateTime> _prov_fecha_registro;
		
		private EntitySet<tbl_proveedor_categoria> _tbl_proveedor_categoria;
		
		private EntitySet<tbl_producto> _tbl_producto;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onprov_idChanging(int value);
    partial void Onprov_idChanged();
    partial void Onprov_nombreChanging(string value);
    partial void Onprov_nombreChanged();
    partial void Onprov_contactoChanging(string value);
    partial void Onprov_contactoChanged();
    partial void Onprov_emailChanging(string value);
    partial void Onprov_emailChanged();
    partial void Onprov_estadoChanging(System.Nullable<bool> value);
    partial void Onprov_estadoChanged();
    partial void Onprov_fecha_registroChanging(System.Nullable<System.DateTime> value);
    partial void Onprov_fecha_registroChanged();
    #endregion
		
		public tbl_proveedor()
		{
			this._tbl_proveedor_categoria = new EntitySet<tbl_proveedor_categoria>(new Action<tbl_proveedor_categoria>(this.attach_tbl_proveedor_categoria), new Action<tbl_proveedor_categoria>(this.detach_tbl_proveedor_categoria));
			this._tbl_producto = new EntitySet<tbl_producto>(new Action<tbl_producto>(this.attach_tbl_producto), new Action<tbl_producto>(this.detach_tbl_producto));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_prov_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int prov_id
		{
			get
			{
				return this._prov_id;
			}
			set
			{
				if ((this._prov_id != value))
				{
					this.Onprov_idChanging(value);
					this.SendPropertyChanging();
					this._prov_id = value;
					this.SendPropertyChanged("prov_id");
					this.Onprov_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_prov_nombre", DbType="VarChar(150) NOT NULL", CanBeNull=false)]
		public string prov_nombre
		{
			get
			{
				return this._prov_nombre;
			}
			set
			{
				if ((this._prov_nombre != value))
				{
					this.Onprov_nombreChanging(value);
					this.SendPropertyChanging();
					this._prov_nombre = value;
					this.SendPropertyChanged("prov_nombre");
					this.Onprov_nombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_prov_contacto", DbType="VarChar(100)")]
		public string prov_contacto
		{
			get
			{
				return this._prov_contacto;
			}
			set
			{
				if ((this._prov_contacto != value))
				{
					this.Onprov_contactoChanging(value);
					this.SendPropertyChanging();
					this._prov_contacto = value;
					this.SendPropertyChanged("prov_contacto");
					this.Onprov_contactoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_prov_email", DbType="VarChar(150)")]
		public string prov_email
		{
			get
			{
				return this._prov_email;
			}
			set
			{
				if ((this._prov_email != value))
				{
					this.Onprov_emailChanging(value);
					this.SendPropertyChanging();
					this._prov_email = value;
					this.SendPropertyChanged("prov_email");
					this.Onprov_emailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_prov_estado", DbType="Bit")]
		public System.Nullable<bool> prov_estado
		{
			get
			{
				return this._prov_estado;
			}
			set
			{
				if ((this._prov_estado != value))
				{
					this.Onprov_estadoChanging(value);
					this.SendPropertyChanging();
					this._prov_estado = value;
					this.SendPropertyChanged("prov_estado");
					this.Onprov_estadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_prov_fecha_registro", DbType="DateTime")]
		public System.Nullable<System.DateTime> prov_fecha_registro
		{
			get
			{
				return this._prov_fecha_registro;
			}
			set
			{
				if ((this._prov_fecha_registro != value))
				{
					this.Onprov_fecha_registroChanging(value);
					this.SendPropertyChanging();
					this._prov_fecha_registro = value;
					this.SendPropertyChanged("prov_fecha_registro");
					this.Onprov_fecha_registroChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_proveedor_tbl_proveedor_categoria", Storage="_tbl_proveedor_categoria", ThisKey="prov_id", OtherKey="prov_id")]
		public EntitySet<tbl_proveedor_categoria> tbl_proveedor_categoria
		{
			get
			{
				return this._tbl_proveedor_categoria;
			}
			set
			{
				this._tbl_proveedor_categoria.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_proveedor_tbl_producto", Storage="_tbl_producto", ThisKey="prov_id", OtherKey="prov_id")]
		public EntitySet<tbl_producto> tbl_producto
		{
			get
			{
				return this._tbl_producto;
			}
			set
			{
				this._tbl_producto.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tbl_proveedor_categoria(tbl_proveedor_categoria entity)
		{
			this.SendPropertyChanging();
			entity.tbl_proveedor = this;
		}
		
		private void detach_tbl_proveedor_categoria(tbl_proveedor_categoria entity)
		{
			this.SendPropertyChanging();
			entity.tbl_proveedor = null;
		}
		
		private void attach_tbl_producto(tbl_producto entity)
		{
			this.SendPropertyChanging();
			entity.tbl_proveedor = this;
		}
		
		private void detach_tbl_producto(tbl_producto entity)
		{
			this.SendPropertyChanging();
			entity.tbl_proveedor = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_categoria_permitida")]
	public partial class tbl_categoria_permitida : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _cat_nombre;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Oncat_nombreChanging(string value);
    partial void Oncat_nombreChanged();
    #endregion
		
		public tbl_categoria_permitida()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cat_nombre", DbType="VarChar(100) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string cat_nombre
		{
			get
			{
				return this._cat_nombre;
			}
			set
			{
				if ((this._cat_nombre != value))
				{
					this.Oncat_nombreChanging(value);
					this.SendPropertyChanging();
					this._cat_nombre = value;
					this.SendPropertyChanged("cat_nombre");
					this.Oncat_nombreChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_proveedor_categoria")]
	public partial class tbl_proveedor_categoria : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _prov_id;
		
		private int _cat_id;
		
		private System.DateTime _fecha_homologacion;
		
		private EntityRef<tbl_proveedor> _tbl_proveedor;
		
		private EntityRef<tbl_categoria> _tbl_categoria;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onprov_idChanging(int value);
    partial void Onprov_idChanged();
    partial void Oncat_idChanging(int value);
    partial void Oncat_idChanged();
    partial void Onfecha_homologacionChanging(System.DateTime value);
    partial void Onfecha_homologacionChanged();
    #endregion
		
		public tbl_proveedor_categoria()
		{
			this._tbl_proveedor = default(EntityRef<tbl_proveedor>);
			this._tbl_categoria = default(EntityRef<tbl_categoria>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_prov_id", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int prov_id
		{
			get
			{
				return this._prov_id;
			}
			set
			{
				if ((this._prov_id != value))
				{
					if (this._tbl_proveedor.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onprov_idChanging(value);
					this.SendPropertyChanging();
					this._prov_id = value;
					this.SendPropertyChanged("prov_id");
					this.Onprov_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cat_id", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int cat_id
		{
			get
			{
				return this._cat_id;
			}
			set
			{
				if ((this._cat_id != value))
				{
					if (this._tbl_categoria.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Oncat_idChanging(value);
					this.SendPropertyChanging();
					this._cat_id = value;
					this.SendPropertyChanged("cat_id");
					this.Oncat_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fecha_homologacion", DbType="DateTime NOT NULL")]
		public System.DateTime fecha_homologacion
		{
			get
			{
				return this._fecha_homologacion;
			}
			set
			{
				if ((this._fecha_homologacion != value))
				{
					this.Onfecha_homologacionChanging(value);
					this.SendPropertyChanging();
					this._fecha_homologacion = value;
					this.SendPropertyChanged("fecha_homologacion");
					this.Onfecha_homologacionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_proveedor_tbl_proveedor_categoria", Storage="_tbl_proveedor", ThisKey="prov_id", OtherKey="prov_id", IsForeignKey=true)]
		public tbl_proveedor tbl_proveedor
		{
			get
			{
				return this._tbl_proveedor.Entity;
			}
			set
			{
				tbl_proveedor previousValue = this._tbl_proveedor.Entity;
				if (((previousValue != value) 
							|| (this._tbl_proveedor.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tbl_proveedor.Entity = null;
						previousValue.tbl_proveedor_categoria.Remove(this);
					}
					this._tbl_proveedor.Entity = value;
					if ((value != null))
					{
						value.tbl_proveedor_categoria.Add(this);
						this._prov_id = value.prov_id;
					}
					else
					{
						this._prov_id = default(int);
					}
					this.SendPropertyChanged("tbl_proveedor");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_categoria_tbl_proveedor_categoria", Storage="_tbl_categoria", ThisKey="cat_id", OtherKey="cat_id", IsForeignKey=true)]
		public tbl_categoria tbl_categoria
		{
			get
			{
				return this._tbl_categoria.Entity;
			}
			set
			{
				tbl_categoria previousValue = this._tbl_categoria.Entity;
				if (((previousValue != value) 
							|| (this._tbl_categoria.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tbl_categoria.Entity = null;
						previousValue.tbl_proveedor_categoria.Remove(this);
					}
					this._tbl_categoria.Entity = value;
					if ((value != null))
					{
						value.tbl_proveedor_categoria.Add(this);
						this._cat_id = value.cat_id;
					}
					else
					{
						this._cat_id = default(int);
					}
					this.SendPropertyChanged("tbl_categoria");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_categoria")]
	public partial class tbl_categoria : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _cat_id;
		
		private string _cat_nombre;
		
		private string _cat_descripcion;
		
		private bool _cat_estado;
		
		private EntitySet<tbl_proveedor_categoria> _tbl_proveedor_categoria;
		
		private EntitySet<tbl_producto> _tbl_producto;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Oncat_idChanging(int value);
    partial void Oncat_idChanged();
    partial void Oncat_nombreChanging(string value);
    partial void Oncat_nombreChanged();
    partial void Oncat_descripcionChanging(string value);
    partial void Oncat_descripcionChanged();
    partial void Oncat_estadoChanging(bool value);
    partial void Oncat_estadoChanged();
    #endregion
		
		public tbl_categoria()
		{
			this._tbl_proveedor_categoria = new EntitySet<tbl_proveedor_categoria>(new Action<tbl_proveedor_categoria>(this.attach_tbl_proveedor_categoria), new Action<tbl_proveedor_categoria>(this.detach_tbl_proveedor_categoria));
			this._tbl_producto = new EntitySet<tbl_producto>(new Action<tbl_producto>(this.attach_tbl_producto), new Action<tbl_producto>(this.detach_tbl_producto));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cat_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int cat_id
		{
			get
			{
				return this._cat_id;
			}
			set
			{
				if ((this._cat_id != value))
				{
					this.Oncat_idChanging(value);
					this.SendPropertyChanging();
					this._cat_id = value;
					this.SendPropertyChanged("cat_id");
					this.Oncat_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cat_nombre", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string cat_nombre
		{
			get
			{
				return this._cat_nombre;
			}
			set
			{
				if ((this._cat_nombre != value))
				{
					this.Oncat_nombreChanging(value);
					this.SendPropertyChanging();
					this._cat_nombre = value;
					this.SendPropertyChanged("cat_nombre");
					this.Oncat_nombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cat_descripcion", DbType="VarChar(250)")]
		public string cat_descripcion
		{
			get
			{
				return this._cat_descripcion;
			}
			set
			{
				if ((this._cat_descripcion != value))
				{
					this.Oncat_descripcionChanging(value);
					this.SendPropertyChanging();
					this._cat_descripcion = value;
					this.SendPropertyChanged("cat_descripcion");
					this.Oncat_descripcionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cat_estado", DbType="Bit NOT NULL")]
		public bool cat_estado
		{
			get
			{
				return this._cat_estado;
			}
			set
			{
				if ((this._cat_estado != value))
				{
					this.Oncat_estadoChanging(value);
					this.SendPropertyChanging();
					this._cat_estado = value;
					this.SendPropertyChanged("cat_estado");
					this.Oncat_estadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_categoria_tbl_proveedor_categoria", Storage="_tbl_proveedor_categoria", ThisKey="cat_id", OtherKey="cat_id")]
		public EntitySet<tbl_proveedor_categoria> tbl_proveedor_categoria
		{
			get
			{
				return this._tbl_proveedor_categoria;
			}
			set
			{
				this._tbl_proveedor_categoria.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_categoria_tbl_producto", Storage="_tbl_producto", ThisKey="cat_id", OtherKey="cat_id")]
		public EntitySet<tbl_producto> tbl_producto
		{
			get
			{
				return this._tbl_producto;
			}
			set
			{
				this._tbl_producto.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tbl_proveedor_categoria(tbl_proveedor_categoria entity)
		{
			this.SendPropertyChanging();
			entity.tbl_categoria = this;
		}
		
		private void detach_tbl_proveedor_categoria(tbl_proveedor_categoria entity)
		{
			this.SendPropertyChanging();
			entity.tbl_categoria = null;
		}
		
		private void attach_tbl_producto(tbl_producto entity)
		{
			this.SendPropertyChanging();
			entity.tbl_categoria = this;
		}
		
		private void detach_tbl_producto(tbl_producto entity)
		{
			this.SendPropertyChanging();
			entity.tbl_categoria = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_producto")]
	public partial class tbl_producto : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _pro_id;
		
		private string _pro_nombre;
		
		private string _pro_descripcion;
		
		private int _pro_cantidad;
		
		private decimal _pro_precio;
		
		private string _pro_foto_path;
		
		private System.Nullable<bool> _pro_estado;
		
		private System.Nullable<int> _prov_id;
		
		private System.Nullable<System.DateTime> _pro_fecha_registro;
		
		private System.Nullable<int> _cat_id;
		
		private EntitySet<tbl_producto_imagen> _tbl_producto_imagen;
		
		private EntityRef<tbl_categoria> _tbl_categoria;
		
		private EntityRef<tbl_proveedor> _tbl_proveedor;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onpro_idChanging(int value);
    partial void Onpro_idChanged();
    partial void Onpro_nombreChanging(string value);
    partial void Onpro_nombreChanged();
    partial void Onpro_descripcionChanging(string value);
    partial void Onpro_descripcionChanged();
    partial void Onpro_cantidadChanging(int value);
    partial void Onpro_cantidadChanged();
    partial void Onpro_precioChanging(decimal value);
    partial void Onpro_precioChanged();
    partial void Onpro_foto_pathChanging(string value);
    partial void Onpro_foto_pathChanged();
    partial void Onpro_estadoChanging(System.Nullable<bool> value);
    partial void Onpro_estadoChanged();
    partial void Onprov_idChanging(System.Nullable<int> value);
    partial void Onprov_idChanged();
    partial void Onpro_fecha_registroChanging(System.Nullable<System.DateTime> value);
    partial void Onpro_fecha_registroChanged();
    partial void Oncat_idChanging(System.Nullable<int> value);
    partial void Oncat_idChanged();
    #endregion
		
		public tbl_producto()
		{
			this._tbl_producto_imagen = new EntitySet<tbl_producto_imagen>(new Action<tbl_producto_imagen>(this.attach_tbl_producto_imagen), new Action<tbl_producto_imagen>(this.detach_tbl_producto_imagen));
			this._tbl_categoria = default(EntityRef<tbl_categoria>);
			this._tbl_proveedor = default(EntityRef<tbl_proveedor>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pro_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int pro_id
		{
			get
			{
				return this._pro_id;
			}
			set
			{
				if ((this._pro_id != value))
				{
					this.Onpro_idChanging(value);
					this.SendPropertyChanging();
					this._pro_id = value;
					this.SendPropertyChanged("pro_id");
					this.Onpro_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pro_nombre", DbType="VarChar(150) NOT NULL", CanBeNull=false)]
		public string pro_nombre
		{
			get
			{
				return this._pro_nombre;
			}
			set
			{
				if ((this._pro_nombre != value))
				{
					this.Onpro_nombreChanging(value);
					this.SendPropertyChanging();
					this._pro_nombre = value;
					this.SendPropertyChanged("pro_nombre");
					this.Onpro_nombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pro_descripcion", DbType="VarChar(500)")]
		public string pro_descripcion
		{
			get
			{
				return this._pro_descripcion;
			}
			set
			{
				if ((this._pro_descripcion != value))
				{
					this.Onpro_descripcionChanging(value);
					this.SendPropertyChanging();
					this._pro_descripcion = value;
					this.SendPropertyChanged("pro_descripcion");
					this.Onpro_descripcionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pro_cantidad", DbType="Int NOT NULL")]
		public int pro_cantidad
		{
			get
			{
				return this._pro_cantidad;
			}
			set
			{
				if ((this._pro_cantidad != value))
				{
					this.Onpro_cantidadChanging(value);
					this.SendPropertyChanging();
					this._pro_cantidad = value;
					this.SendPropertyChanged("pro_cantidad");
					this.Onpro_cantidadChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pro_precio", DbType="Decimal(18,2) NOT NULL")]
		public decimal pro_precio
		{
			get
			{
				return this._pro_precio;
			}
			set
			{
				if ((this._pro_precio != value))
				{
					this.Onpro_precioChanging(value);
					this.SendPropertyChanging();
					this._pro_precio = value;
					this.SendPropertyChanged("pro_precio");
					this.Onpro_precioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pro_foto_path", DbType="VarChar(500)")]
		public string pro_foto_path
		{
			get
			{
				return this._pro_foto_path;
			}
			set
			{
				if ((this._pro_foto_path != value))
				{
					this.Onpro_foto_pathChanging(value);
					this.SendPropertyChanging();
					this._pro_foto_path = value;
					this.SendPropertyChanged("pro_foto_path");
					this.Onpro_foto_pathChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pro_estado", DbType="Bit")]
		public System.Nullable<bool> pro_estado
		{
			get
			{
				return this._pro_estado;
			}
			set
			{
				if ((this._pro_estado != value))
				{
					this.Onpro_estadoChanging(value);
					this.SendPropertyChanging();
					this._pro_estado = value;
					this.SendPropertyChanged("pro_estado");
					this.Onpro_estadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_prov_id", DbType="Int")]
		public System.Nullable<int> prov_id
		{
			get
			{
				return this._prov_id;
			}
			set
			{
				if ((this._prov_id != value))
				{
					if (this._tbl_proveedor.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onprov_idChanging(value);
					this.SendPropertyChanging();
					this._prov_id = value;
					this.SendPropertyChanged("prov_id");
					this.Onprov_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pro_fecha_registro", DbType="DateTime")]
		public System.Nullable<System.DateTime> pro_fecha_registro
		{
			get
			{
				return this._pro_fecha_registro;
			}
			set
			{
				if ((this._pro_fecha_registro != value))
				{
					this.Onpro_fecha_registroChanging(value);
					this.SendPropertyChanging();
					this._pro_fecha_registro = value;
					this.SendPropertyChanged("pro_fecha_registro");
					this.Onpro_fecha_registroChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cat_id", DbType="Int")]
		public System.Nullable<int> cat_id
		{
			get
			{
				return this._cat_id;
			}
			set
			{
				if ((this._cat_id != value))
				{
					if (this._tbl_categoria.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Oncat_idChanging(value);
					this.SendPropertyChanging();
					this._cat_id = value;
					this.SendPropertyChanged("cat_id");
					this.Oncat_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_producto_tbl_producto_imagen", Storage="_tbl_producto_imagen", ThisKey="pro_id", OtherKey="pro_id")]
		public EntitySet<tbl_producto_imagen> tbl_producto_imagen
		{
			get
			{
				return this._tbl_producto_imagen;
			}
			set
			{
				this._tbl_producto_imagen.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_categoria_tbl_producto", Storage="_tbl_categoria", ThisKey="cat_id", OtherKey="cat_id", IsForeignKey=true)]
		public tbl_categoria tbl_categoria
		{
			get
			{
				return this._tbl_categoria.Entity;
			}
			set
			{
				tbl_categoria previousValue = this._tbl_categoria.Entity;
				if (((previousValue != value) 
							|| (this._tbl_categoria.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tbl_categoria.Entity = null;
						previousValue.tbl_producto.Remove(this);
					}
					this._tbl_categoria.Entity = value;
					if ((value != null))
					{
						value.tbl_producto.Add(this);
						this._cat_id = value.cat_id;
					}
					else
					{
						this._cat_id = default(Nullable<int>);
					}
					this.SendPropertyChanged("tbl_categoria");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_proveedor_tbl_producto", Storage="_tbl_proveedor", ThisKey="prov_id", OtherKey="prov_id", IsForeignKey=true)]
		public tbl_proveedor tbl_proveedor
		{
			get
			{
				return this._tbl_proveedor.Entity;
			}
			set
			{
				tbl_proveedor previousValue = this._tbl_proveedor.Entity;
				if (((previousValue != value) 
							|| (this._tbl_proveedor.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tbl_proveedor.Entity = null;
						previousValue.tbl_producto.Remove(this);
					}
					this._tbl_proveedor.Entity = value;
					if ((value != null))
					{
						value.tbl_producto.Add(this);
						this._prov_id = value.prov_id;
					}
					else
					{
						this._prov_id = default(Nullable<int>);
					}
					this.SendPropertyChanged("tbl_proveedor");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tbl_producto_imagen(tbl_producto_imagen entity)
		{
			this.SendPropertyChanging();
			entity.tbl_producto = this;
		}
		
		private void detach_tbl_producto_imagen(tbl_producto_imagen entity)
		{
			this.SendPropertyChanging();
			entity.tbl_producto = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_producto_imagen")]
	public partial class tbl_producto_imagen : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _img_id;
		
		private System.Nullable<int> _pro_id;
		
		private string _img_path;
		
		private EntityRef<tbl_producto> _tbl_producto;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onimg_idChanging(int value);
    partial void Onimg_idChanged();
    partial void Onpro_idChanging(System.Nullable<int> value);
    partial void Onpro_idChanged();
    partial void Onimg_pathChanging(string value);
    partial void Onimg_pathChanged();
    #endregion
		
		public tbl_producto_imagen()
		{
			this._tbl_producto = default(EntityRef<tbl_producto>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_img_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int img_id
		{
			get
			{
				return this._img_id;
			}
			set
			{
				if ((this._img_id != value))
				{
					this.Onimg_idChanging(value);
					this.SendPropertyChanging();
					this._img_id = value;
					this.SendPropertyChanged("img_id");
					this.Onimg_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pro_id", DbType="Int")]
		public System.Nullable<int> pro_id
		{
			get
			{
				return this._pro_id;
			}
			set
			{
				if ((this._pro_id != value))
				{
					if (this._tbl_producto.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onpro_idChanging(value);
					this.SendPropertyChanging();
					this._pro_id = value;
					this.SendPropertyChanged("pro_id");
					this.Onpro_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_img_path", DbType="NVarChar(250) NOT NULL", CanBeNull=false)]
		public string img_path
		{
			get
			{
				return this._img_path;
			}
			set
			{
				if ((this._img_path != value))
				{
					this.Onimg_pathChanging(value);
					this.SendPropertyChanging();
					this._img_path = value;
					this.SendPropertyChanged("img_path");
					this.Onimg_pathChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_producto_tbl_producto_imagen", Storage="_tbl_producto", ThisKey="pro_id", OtherKey="pro_id", IsForeignKey=true, DeleteRule="CASCADE")]
		public tbl_producto tbl_producto
		{
			get
			{
				return this._tbl_producto.Entity;
			}
			set
			{
				tbl_producto previousValue = this._tbl_producto.Entity;
				if (((previousValue != value) 
							|| (this._tbl_producto.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tbl_producto.Entity = null;
						previousValue.tbl_producto_imagen.Remove(this);
					}
					this._tbl_producto.Entity = value;
					if ((value != null))
					{
						value.tbl_producto_imagen.Add(this);
						this._pro_id = value.pro_id;
					}
					else
					{
						this._pro_id = default(Nullable<int>);
					}
					this.SendPropertyChanged("tbl_producto");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
